// Code generated by mockery v2.52.2. DO NOT EDIT.

package fake

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Message is an autogenerated mock type for the Message type
type Message struct {
	mock.Mock
}

// Attribute provides a mock function with given fields: key
func (_m *Message) Attribute(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Attribute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Attributes provides a mock function with no fields
func (_m *Message) Attributes() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Attributes")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// BackedOff provides a mock function with no fields
func (_m *Message) BackedOff() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BackedOff")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Backoff provides a mock function with given fields: delay
func (_m *Message) Backoff(delay time.Duration) {
	_m.Called(delay)
}

// Body provides a mock function with no fields
func (_m *Message) Body() []byte {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Decode provides a mock function with given fields: out
func (_m *Message) Decode(out interface{}) error {
	ret := _m.Called(out)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecodeMessage provides a mock function with given fields: out
func (_m *Message) DecodeMessage(out interface{}) error {
	ret := _m.Called(out)

	if len(ret) == 0 {
		panic("no return value specified for DecodeMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Dispatch provides a mock function with no fields
func (_m *Message) Dispatch() {
	_m.Called()
}

// Identifier provides a mock function with no fields
func (_m *Message) Identifier() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Identifier")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Message provides a mock function with no fields
func (_m *Message) Message() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Message")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Metadata provides a mock function with no fields
func (_m *Message) Metadata() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// SystemAttributeByKey provides a mock function with given fields: key
func (_m *Message) SystemAttributeByKey(key string) string {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for SystemAttributeByKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SystemAttributes provides a mock function with no fields
func (_m *Message) SystemAttributes() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SystemAttributes")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// TimeStamp provides a mock function with no fields
func (_m *Message) TimeStamp() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TimeStamp")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// NewMessage creates a new instance of Message. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Message {
	mock := &Message{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
