// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fake

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sns"
	mock "github.com/stretchr/testify/mock"
)

// NewSNSClient creates a new instance of SNSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSNSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SNSClient {
	mock := &SNSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SNSClient is an autogenerated mock type for the SNSClient type
type SNSClient struct {
	mock.Mock
}

type SNSClient_Expecter struct {
	mock *mock.Mock
}

func (_m *SNSClient) EXPECT() *SNSClient_Expecter {
	return &SNSClient_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type SNSClient
func (_mock *SNSClient) Publish(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *sns.PublishOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) (*sns.PublishOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) *sns.PublishOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.PublishOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sns.PublishInput, ...func(*sns.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SNSClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type SNSClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sns.PublishInput
//   - optFns ...func(*sns.Options)
func (_e *SNSClient_Expecter) Publish(ctx interface{}, params interface{}, optFns ...interface{}) *SNSClient_Publish_Call {
	return &SNSClient_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *SNSClient_Publish_Call) Run(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options))) *SNSClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sns.PublishInput
		if args[1] != nil {
			arg1 = args[1].(*sns.PublishInput)
		}
		var arg2 []func(*sns.Options)
		var variadicArgs []func(*sns.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sns.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SNSClient_Publish_Call) Return(publishOutput *sns.PublishOutput, err error) *SNSClient_Publish_Call {
	_c.Call.Return(publishOutput, err)
	return _c
}

func (_c *SNSClient_Publish_Call) RunAndReturn(run func(ctx context.Context, params *sns.PublishInput, optFns ...func(*sns.Options)) (*sns.PublishOutput, error)) *SNSClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishBatch provides a mock function for the type SNSClient
func (_mock *SNSClient) PublishBatch(ctx context.Context, params *sns.PublishBatchInput, optFns ...func(*sns.Options)) (*sns.PublishBatchOutput, error) {
	var tmpRet mock.Arguments
	if len(optFns) > 0 {
		tmpRet = _mock.Called(ctx, params, optFns)
	} else {
		tmpRet = _mock.Called(ctx, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PublishBatch")
	}

	var r0 *sns.PublishBatchOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishBatchInput, ...func(*sns.Options)) (*sns.PublishBatchOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sns.PublishBatchInput, ...func(*sns.Options)) *sns.PublishBatchOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sns.PublishBatchOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sns.PublishBatchInput, ...func(*sns.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SNSClient_PublishBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishBatch'
type SNSClient_PublishBatch_Call struct {
	*mock.Call
}

// PublishBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - params *sns.PublishBatchInput
//   - optFns ...func(*sns.Options)
func (_e *SNSClient_Expecter) PublishBatch(ctx interface{}, params interface{}, optFns ...interface{}) *SNSClient_PublishBatch_Call {
	return &SNSClient_PublishBatch_Call{Call: _e.mock.On("PublishBatch",
		append([]interface{}{ctx, params}, optFns...)...)}
}

func (_c *SNSClient_PublishBatch_Call) Run(run func(ctx context.Context, params *sns.PublishBatchInput, optFns ...func(*sns.Options))) *SNSClient_PublishBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sns.PublishBatchInput
		if args[1] != nil {
			arg1 = args[1].(*sns.PublishBatchInput)
		}
		var arg2 []func(*sns.Options)
		var variadicArgs []func(*sns.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*sns.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SNSClient_PublishBatch_Call) Return(publishBatchOutput *sns.PublishBatchOutput, err error) *SNSClient_PublishBatch_Call {
	_c.Call.Return(publishBatchOutput, err)
	return _c
}

func (_c *SNSClient_PublishBatch_Call) RunAndReturn(run func(ctx context.Context, params *sns.PublishBatchInput, optFns ...func(*sns.Options)) (*sns.PublishBatchOutput, error)) *SNSClient_PublishBatch_Call {
	_c.Call.Return(run)
	return _c
}
