name: Go CI

on:
  push:
    branches: ["main"]
    paths:
      - "**.go"
      - go.mod
  pull_request:
    branches: ["main"]
    paths:
      - "**.go"
      - go.mod

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Test
        run: go test -timeout 1m -race -covermode=atomic -coverprofile=tmp.out ./... && cat tmp.out | grep -Ev 'example|fake' > geral.out  && go tool cover -func=geral.out

  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1
          args: --timeout 3m --config .golangci.yml
